### ISSUE TITLE
`p11-kit server` Results Undefined Error `cannot determine runtime directory` 

### ISSUE THREAD

**Issue by CaptainYukinoshitaHachiman** [OpenSC/OpenSC#2485]
### Problem Description

macOS Monterey 12.1 (21C52) (arm)
OpenSC-0.22.0-rc1-74-gc902e199, rev: c902e199, commit-time: 2021-08-10 11:09:03 +0200

Running `p11-kit server pkcs11:model=p11-kit-trust;manufacturer=PKCS%2311%20Kit;serial=1;token=System%20Trust` results in `(p11-kit:30006) message: cannot determine runtime directory: Undefined error: 0`

### Logs

When p11-kit server is run with debug = 3 in opensc.conf, no log is generated.

**Comment by dengert** [comment]
This does not look like an OpenSC problem, but a p11-kit problem. "model=p11-kit-trust;manufacturer=PKCS%2311%20Kit;serial=1;token=System%20Trust" is internal to p11-kit.

Do  you need to add `--provider`

What is output of `p11-kit list-modules`?

**Comment by CaptainYukinoshitaHachiman** [comment]
Sorry for asking in the wrong place (I am quite new to these things) Should I close this issue or can I keep it open?

I have tried to add `--provider`, but that doesn't seem to change anything (same error, the library I referenced does exist)
The output of `p11-kit list-modules` is as follows:

```
p11-kit-trust: p11-kit-trust.so
    library-description: PKCS#11 Kit Trust Module
    library-manufacturer: PKCS#11 Kit
    library-version: 0.24
    token: System Trust
        manufacturer: PKCS#11 Kit
        model: p11-kit-trust
        serial-number: 1
        hardware-version: 0.24
        flags:
               write-protected
               token-initialized
```
