### ISSUE TITLE
cannot use the keys in two slots at the same time

### ISSUE THREAD

**Issue by yuchunyun** [OpenSC/OpenSC#2840]
version: opensc-0.20.0-4.el8.x86_64
have different keys in two modules, and use p11-kit to load two pkcs#11 modules,  then using the command `pkcs11-tool --module /usr/local/lib64/libp11-kit.so -L` can also see two slots
```
# pkcs11-tool --module /usr/local/lib64/libp11-kit.so -L
Available slots:
Slot 0 (0x11): SoftHSM slot ID 0x77e3939
  token label        : zdns
  token manufacturer : SoftHSM project
  token model        : SoftHSM v2
  token flags        : login required, rng, token initialized, PIN initialized, other flags=0x20
  hardware version   : 2.6
  firmware version   : 2.6
  serial num         : 8fd5142c077e3939
  pin min/max        : 4/255
Slot 1 (0x12): SoftHSM slot ID 0x1
  token state:   uninitialized
Slot 2 (0x13): SoftHSM slot ID 0x2e3aa9bc
  token label        : zdns
  token manufacturer : SoftHSM project
  token model        : SoftHSM v2
  token flags        : login required, rng, token initialized, PIN initialized, other flags=0x20
  hardware version   : 2.6
  firmware version   : 2.6
  serial num         : 616461c3ae3aa9bc
  pin min/max        : 4/255
Slot 3 (0x14): SoftHSM slot ID 0x1
  token state:   uninitialized
```

using the command `pkcs11-tool --module /usr/local/lib64/libp11-kit.so -O` can only see the key in one slot,
```
# pkcs11-tool --module /usr/local/lib64/libp11-kit.so -O
Using slot 0 with a present token (0x11)
Public Key Object; EC  EC_POINT 256 bits
  EC_POINT:   044104bb0a7e5267022fbad7dcdfe03a110ab7aaed19e738021c27fa52daf46f40d08c778fc5f0364fb3da9800e5e2c53112775d2558a26291538bf0dac6a8f2a904fa
  EC_PARAMS:  06082a8648ce3d030107
  label:      test.top. ZSK
  ID:         34dcf3e8c5b491336cd0a3ba05f44182f726b7db
  Usage:      encrypt, verify, wrap
  Access:     local
```
 unless add the `--slot-index 2` parameter to see the key in both slots. 
```
# pkcs11-tool --module /usr/local/lib64/libp11-kit.so --slot-index 2 -O 
Using slot with index 2 (0x13)
Public Key Object; EC  EC_POINT 256 bits
  EC_POINT:   044104bae800ad0b503bd78b260f45d434f74864b22f65b5ec8478b2172691881a243ff2966c720d52126f210b268eaf7efa364964ccfe3c5932b9e9c9e08fd27514e1
  EC_PARAMS:  06082a8648ce3d030107
  label:      test.top. KSK
  ID:         e599b9a79c1a1f1bacebee4ee37c25ca12daa9d4
  Usage:      encrypt, verify, wrap
  Access:     local
Public Key Object; EC  EC_POINT 256 bits
  EC_POINT:   04410485eee053f99c26b568a077095a31c8f53ef85e8fb28f702a563411271bceccf354b10b7e7b32909c3adf61a9a76725a0f1ad24d0f50a6c899e9406cd593a8b80
  EC_PARAMS:  06082a8648ce3d030107
  label:      test.top. ZSK
  ID:         6ad0e35adc025f5002231af8ee3924f3e66693d1
  Usage:      encrypt, verify, wrap
  Access:     local
```
Is there any way to display the keys in all slots at the same time, my ultimate goal is to use p11-kit in the knot's dnssec and then use the keys in both modules for signature

**Comment by dengert** [comment]
OpenSC's pkcs11-tool and p11kit's p11tool both can list all the slots and tokens in slots but other operations are done against a specific token.  

The limitation is in the tools, not PKCS11.

https://datatracker.ietf.org/doc/html/rfc7512  addresses part of the problem, by having a standard way to identify a token and objects on the token. Slots change so are not a good way to identify a specific token. 
RFC 7512 can select a token based on "serial=" or "token=". 

I am not familiar with "knot's dnssec" But a quick search found:  https://www.knot-dns.cz/docs/2.4/singlehtml/ 
says it supports RFC 7512. 

p11-kit also supports RFC 7512:

https://www.redhat.com/en/blog/consistent-pkcs-11-support-red-hat-enterprise-linux-8  gives some examples using

**Comment by dengert** [comment]
Also note https://www.knot-dns.cz/docs/2.4/singlehtml/
gives an example using RFC 7512 and softhsm2:
`"pkcs11:token=knot;pin-value=1234 /usr/lib64/pkcs11/libsofthsm2.so"`

Your example only show using using one module
So if all your keys are in softhsm2 you don't need p11kit. 

In you example both tokens have the same label: zdns
so will use "serial=". Your first token has one key, so don't really need to add "id=." 
Your  second token has 2 keys, so need to select one or the other. 

So your config file using your example could have:
``` 
keystore:
  - id: token1key1
    backend: pkcs11
    config: "pkcs11:serial=8fd5142c077e3939;id=34dcf3e8c5b491336cd0a3ba05f44182f726b7db;pin-value=1111 /usr/lib64/pkcs11/libsofthsm2.so"

keystore:
  - id: token2key1
    backend: pkcs11
    config: "pkcs11:serial=e599b9a79c1a1f1bacebee4ee37c25ca12daa9d4db;pin-value=2222 /usr/lib64/pkcs11/libsofthsm2.so"

keystore:
  - id: token2key2
    backend: pkcs11
    config: "pkcs11:serial=616461c3ae3aa9bc;id=6ad0e35adc025f5002231af8ee3924f3e66693d1;pin-value=2222 /usr/lib64/pkcs11/libsofthsm2.so"
```
